# Generated by Django 5.1.5 on 2025-04-02 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("company_address", models.TextField(blank=True, null=True)),
                ("company_email", models.EmailField(max_length=254, unique=True)),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
